server:
  port: 9001

spring:
  http:
    encoding:
      charset: utf-8
      enabled: true
  thymeleaf:
    cache: false
  data:
    mongodb:
      uri: mongodb://localhost:27017/recommender?maxIdleTimeMS=86400000
logging:
  config: classpath:logback-spring.xml

redis:
  database: 0           # Redis服务器数据库
  host: localhost    # Redis服务器地址
  port: 6379            # Redis服务器连接端口
  timeout: 6000ms       # 连接超时时间（毫秒）
  jedis:
    pool:
      max-active: 200   # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10      # 连接池中的最大空闲连接
      min-idle: 0       # 连接池中的最小空闲连接